#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/config/functions"

procfile-picker-post-extract() {
  declare APP="$1" TMP_WORK_DIR="$2"

  pushd "$TMP_WORK_DIR" > /dev/null

  DOKKU_PROCFILE=$(config_get "$APP" "DOKKU_PROCFILE" || true)
  if [[ -n "$DOKKU_PROCFILE" ]] && [[ -f "$DOKKU_PROCFILE" ]]; then
    dokku_log_info1 "Overwriting Procfile with $DOKKU_PROCFILE"
    mv "$DOKKU_PROCFILE" Procfile
  fi
  popd > /dev/null
}

procfile-picker-post-extract "$@"
